### PR TITLE
Update Installation Docs with Support for Ubuntu + CentOS

### PR DESCRIPTION
**Pull request by rmrice**
- Added doc outlining detailed instructions for installation on fresh CentOS instance
- Added more specific instructions for building from source on Ubuntu 16.04 (from https://github.com/klokantech/tileserver-gl/issues/68)
- Cleaned up `installation.rst` just a bit

### CODE REVIEW

**Comment by zhali** [comment]
hi, @rmrice ,is there a Dockfile base on CentOS instance ? i want to make a tileserver-gl image with Centos+node

**Comment by hoenic07** [comment]
@zhali : I have created a docker file + adapted `run.sh`. I have not checked it in anywhere, therefore I uploaded it here:
[TileServerCentOs.zip](https://github.com/klokantech/tileserver-gl/files/1546930/TileServerCentOs.zip)

**Comment by zhali** [comment]
@hoenic07 wow~ you are so quick, thank you! i am  try it now

**Comment by zhali** [comment]
@hoenic07 use your plan, i have build my image, when run it : 
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/usr/src/app/run_cos.sh\": permission denied".

**Comment by hoenic07** [comment]
@zhali : You need to give the file execute permission first (from outside the docker container). E.g. with `chmod +x run_cos.sh`

**Comment by zhali** [comment]
@hoenic07 : thank you , add "RUN chmod 755 /usr/src/app/run_cos.sh"

**Comment by zhali** [comment]
@hoenic07 : 
docker run -it -v $(pwd):/data -p 8080:80 zhali/centos-tileserver-gl
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.12.2
npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "-d" "start"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

maybe need to add start to package.json, how?

**Comment by acalcutt** [comment]
These instuctions are very outdated now. I'm going to close this. feel free to improve the current directions. We are mainly recommending Ubuntu 20.04 / MacOS 12 (amd64/arm64)  on node 18 right now.

**Pull request closed without merging**
