### PR TITLE
Fix HUP kill not reloading config

### PR DESCRIPTION
**Pull request by acalcutt**
This is a fix for https://github.com/maptiler/tileserver-gl/issues/629, which was broken in the syntax change of https://github.com/maptiler/tileserver-gl/pull/606

After looking at the code changes, it seems like the sections of code that handles SIGINT/SIGHUP and restarting was not being used anymore. This change renames the functions a bit so the SIGINT/SIGHUP code is actually used.

### CODE REVIEW

**Comment by zstadler** [comment]
I have tested this PR under Docker. Reloading of an updated config file works in both ways:
- The documented preferred way: `docker kill -s HUP tileserver-gl`
- The older way: `docker exec tileserver-gl bash -c 'kill -HUP $(ls -l /proc/*/exe | sed -n "/\/node$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p")`

**Review by mnutt — APPROVED** [review]
I suspect that clearing the require cache might have been to give the ability to reload `options.dataDecorator` which is loaded via `require()`. IMO that seems like it's approaching ad-hoc hot-reloading territory and I think it's fine to not support.

**Comment by zstadler** [comment]
Please consider resolving #629

**Comment by acalcutt** [comment]
I'm planning to resolve it after the docker is updated

**Pull request merged**
