### PR TITLE
feat: add progressive rendering option for static jpeg images

### PR DESCRIPTION
**Pull request by samuel-git**
Adds support for progessive rendering of static jpeg images via the ``formatOptions``.
In my testing, progressive jpegs were ~2% smaller in filesize than their non-progressive counterparts.
They also 'feel' faster because they become more sharp while loading instead of loading in rows from top to bottom.

Also updated the section in the docs.

### CODE REVIEW

**Comment by acalcutt** [comment]
seems like a good addition. can you run 'npm run lint:js:fix' on this to fix the ci lint error

**Comment by samuel-git** [comment]
> seems like a good addition. can you run 'npm run lint:js:fix' on this to fix the ci lint error

Thanks @acalcutt for the heads up, updated the commit.

**Comment by acalcutt** [comment]
The only other commend I have is it would be nice if the readme included an emable of what it want for boolean. Does it want [0 or 1] or [true or false]

**Comment by samuel-git** [comment]
Thanks, updated!

**Review by acalcutt — APPROVED** [review]

**Pull request merged**
