### PR TITLE
Launch Xvfb only if needed

### LINKED ISSUE #794: Restarting container with docker restart <> results in xvfb error
I deployed a tileserver-gl with the following image:  maptiler/tileserver-gl:v4.4.8

docker run -dt --name tileserver-gl -h tileserver-gt -v $(pwd):/data -p 9999:8080 maptiler/tileserver-gl:v4.4.8

When restarting the container because i changed the configuration the following error occurs: 

```
(EE) 
Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
(EE) 
Starting tileserver-gl v4.4.9
Using specified config file from config.json
Starting server
Listening at http://[::]:8080/
Startup complete
```
tileserver-gl doesnt work then anymore. 

There fore i created the pullrequest to fix this: 

https://github.com/maptiler/tileserver-gl/pull/790

### PR DESCRIPTION
**Pull request by zstadler**
Resolve #794

### CODE REVIEW

**Comment by zstadler** [comment]
Restart now works w/o an error:

```
maptiles-tileserver-gl-legend-1  | Starting tileserver-gl v4.1.1
maptiles-tileserver-gl-legend-1  | Using specified config file from /styles/tileserver-gl.json
maptiles-tileserver-gl-legend-1  | Starting server
maptiles-tileserver-gl-legend-1  | Listening at http://[::]:80/
maptiles-tileserver-gl-legend-1  | Startup complete
maptiles-tileserver-gl-legend-1  | Caught signal 15, stopping gracefully
maptiles-tileserver-gl-legend-1  | Terminated
maptiles-tileserver-gl-legend-1  | Starting tileserver-gl v4.1.1
maptiles-tileserver-gl-legend-1  | Using specified config file from /styles/tileserver-gl.json
maptiles-tileserver-gl-legend-1  | Starting server
maptiles-tileserver-gl-legend-1  | Listening at http://[::]:80/
maptiles-tileserver-gl-legend-1  | Startup complete
```

**Comment by acalcutt** [comment]
Is this actually showing the current version working? the log shows an older version.

**Comment by acalcutt** [comment]
After testing this I don't think it helps the issue. It seems on a docker restart the xvfb is getting killed and is leaving behind a lock file. xvfb no longer seems to be running after the docker restart like I initially thought.

Testing this fix like the following still fails. You can see when I loaf a page it can't find X buffer and crashes.
```
root@mapgen2:/opt/data_test# docker build -t 1253 -f Dockerfile .
root@mapgen2:/opt/data_test# docker run -dt --name 1253-3 -h tileserver-gt -v $(pwd):/data -p 9999:8080 1253:latest
891774f0cc79203502051a523e86f203f57f148d9b508de7507522d7eb5c0b63
root@mapgen2:/opt/data_test# docker restart 1253-3
1253-3
root@mapgen2:/opt/data_test# docker container logs 1253-3
Starting tileserver-gl v4.4.9
No MBTiles specified, using output.mbtiles
[INFO] Automatically creating config file for output.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8080/
Startup complete
Caught signal SIGTERM, stopping gracefully
(EE)
Fatal server error:
(EE) Server is already active for display 99
        If this server is no longer running, remove /tmp/.X99-lock
        and start again.
(EE)
Starting tileserver-gl v4.4.9
No MBTiles specified, using output.mbtiles
[INFO] Automatically creating config file for output.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8080/
Startup complete
```

I also tested the fix in https://github.com/maptiler/tileserver-gl/pull/790 , and deleting the lock file does actually work because it allows xvfb to restart itself.

```
root@mapgen2:/opt/data_test# docker run -dt --name 105-1 -h tileserver-gt -v $(pwd):/data -p 9999:8080 105:latest
8cc2460b6dea3cb900ecbec7b4c755db399b20eb890210131d17781496f3b2cb
root@mapgen2:/opt/data_test# docker restart 105-1
105-1
root@mapgen2:/opt/data_test# docker container logs 105-1
Starting tileserver-gl v4.4.9
No MBTiles specified, using output.mbtiles
[INFO] Automatically creating config file for output.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8080/
Startup complete
Caught signal SIGTERM, stopping gracefully
Starting tileserver-gl v4.4.9
No MBTiles specified, using output.mbtiles
[INFO] Automatically creating config file for output.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8080/
Startup complete
Startup complete
GET /styles/basic-preview/?raster 304 - - 23.081 ms
GET /maplibre-gl.css 304 - - 1.344 ms
GET /maplibre-gl-inspect.css 304 - - 1.599 ms
GET /L.TileLayer.NoGap.js 304 - - 1.563 ms
GET /leaflet.css 304 - - 1.605 ms
GET /leaflet.js 304 - - 1.620 ms
GET /leaflet-hash.js 304 - - 1.658 ms
GET /maplibre-gl.js 304 - - 0.259 ms
GET /maplibre-gl-inspect.min.js 304 - - 0.401 ms
GET /styles/basic-preview.json 304 - - 2.113 ms
GET /favicon.ico 304 - - 1.032 ms
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open X display.
```

**Comment by acalcutt** [comment]
Issue Fixed by https://github.com/maptiler/tileserver-gl/pull/790

**Pull request closed without merging**
