### PR TITLE
Add markers to static map endpoint

### PR DESCRIPTION
**Pull request by LEinfeldt**
I've added the functionality to add a single marker or serveral markers in a static map. The approach is similar to the endpoint in google maps.

Single marker with property ``center`` creates a map with a centered marker.
``marker={lng},{lat}`` creates a marker at this location.
Same is possible for ``markers={lng},{lat}|{lng}{lat}|....``

### CODE REVIEW

**Comment by alewin** [comment]
Thanks @LEinfeldt 
it would be nice to add a custom image to the markers, as google maps does
`maps.googleapis.com/maps/api/staticmap?zoom=17&size=512x512&maptype=hybrid&markers=icon:http://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico|34.052230,-118.243680`

Do you think it's possible?

**Comment by nexttoyou** [comment]
> I've added the functionality to add a single marker or serveral markers in a static map. The approach is similar to the endpoint in google maps.

Great work! Hopefully it will be implemented like this as I’m absolutely unable to do the same with static maps and Mapnik.

**Comment by prasadrajuv** [comment]
marker added marker=center but it is very small to actual size not able to observed particularly. the other option marker= path
not able to see any marker may be it mixed with path

**Comment by Fiorello** [comment]
Hi,
when this feature will be merge?

**Comment by mnutt** [comment]
I have an alternate implementation of markers in the branch linked from https://github.com/maptiler/tileserver-gl/issues/537. It allows for remote image URLs, references (so that you don't have to repeat long remote image URLs and make the URL too long) and a recolorable marker. (similar to Mapbox SDF but developed independently) I adapted it from something that has been running in production for many years.

**Comment by Tobeyforce** [comment]
Anyone fancy setting up a docker image with one of these pull requests, where marker support has been added? It looks unclear to me whether a merge is on the table in the near future. This seems like such an important feature, why would anyone use static maps without being able to place anything on it?

**Comment by mnutt** [comment]
@Tobeyforce you're welcome to try out my implementation here: 

https://hub.docker.com/r/mnutt/tileserver-gl 

It has the following features/caveats:
* choose your own marker color hex value as well as size (small, medium, large)
* specify a different external image URL for each marker
* "references" help keep URL length down when you have a lot of markers
* this generates markers by actually placing the icons as images on the map, as a result:
  * there's a slight bit of premultiplication weirdness involving transparent icons that I'm hoping to resolve soon with mapbox-gl-native updates
  * if icons are too close together, only one gets shown (this might be considered a feature, or not...)

This uses a bespoke URL format but it's pretty simple IMO. Right now it's part of the URL path (`/styles/basic-preview/static/[marker-string]/auto/800x600.png`), but I think it might eventually make more sense to pass marker styles as query params, e.g. `/styles/basic-preview/static/auto/800x600.png?marker[]=pin-l+ff00000(8.536,47.379)&marker[]=url-http%3A%2F%2Flocalhost%3A8080...`. That way it might be a bit more composable than it is now. Either way, this docker image is a work-in-progress.

image

The UI above is available via the "Static Editor" link from the main page:

image

**Comment by acalcutt** [comment]
This PR https://github.com/maptiler/tileserver-gl/pull/619 has been merged in fovor of this on. closing this

**Pull request closed without merging**
