### PR TITLE
Minimal maplibre-gl-native changes + docker build update

### PR DESCRIPTION
**Pull request by acalcutt**
These are minimal changes to switch tileserver-gl to use maplibre-gl-native and maplibre-gl-style-spec. 

After this change, the OS in the docker images requires an update to support the [maplibre-gl-native binaries](https://github.com/maplibre/maplibre-gl-native/releases/tag/node-v5.0.1-pre.0) which are built on ubuntu-20.04

I have also updated the dependencies in the documentation to match what is needed for maplibre-gl-native

Without any other changes, it seems this works on node 10 - node 16. node 18 failed

### CODE REVIEW

**Comment by roblabs** [comment]
Thanks, @acalcutt for the upgrades and for pushing this forward.

---

I gave the fork a spin, [`WifiDB:maplibre-native`](https://github.com/WifiDB/tileserver-gl/tree/maplibre-native), but I was not able to get the Dockerfile to run and serve Zurich MBTiles.

* The Docker build works
* The Docker server _appears_ to be running (log below)
* Firefox reports _"The connection was reset"_.

I'm using my usual [tileserver-gl usage steps](https://github.com/roblabs/openmaptiles-ios-demo/blob/master/OSM2VectorTiles/tileserver-gl/config.zurich.json#L8).

Maybe I'm missing a step?!?  

---

```bash
# 1. edit, but don't commit, simple changes to `package.json` to expose version of your local build

# 2. Make a local Docker image
docker build -t tileserver-gl .

# 3.  Use that local Docker image
#     `zurich_switzerland.mbtiles` already in root folder
docker run --rm -it -v $(pwd):/data -p 8080:80 tileserver-gl --verbose

# 
open http://localhost:8080
```

---

### Docker log

Server appears to be running fine. changed the `name` in `package.json` to verify which Docker image I'm using.

> Starting *tileserver-gl-locallybuilt v3.1.1*
No MBTiles specified, using zurich_switzerland.mbtiles
[INFO] Automatically creating config file for zurich_switzerland.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
{
  "options": {
    "paths": {
      "root": "/app/node_modules/tileserver-gl-styles",
      "fonts": "fonts",
      "styles": "styles",
      "mbtiles": "/data"
    }
  },
  "styles": {
    "basic-preview": {
      "style": "basic-preview/style.json",
      "tilejson": {
        "bounds": [
          8.275,
          47.225,
          8.8,
          47.533
        ]
      }
    }
  },
  "data": {
    "v3": {
      "mbtiles": "zurich_switzerland.mbtiles"
    }
  }
}
Starting server
Listening at http://[::]:8080/
Startup complete

**Comment by acalcutt** [comment]
Maybe download the mbtiles first. I seem to remember  in the docker it wasn't able to download to the current directory

wget https://github.com/acalcutt/tileserver-gl/releases/download/test_data/zurich_switzerland.mbtiles
docker run --rm -it -v $(pwd):/data -p 8080:80 tileserver-gl --verbose

**Comment by acalcutt** [comment]
In https://github.com/acalcutt/tileserver-gl/ I actually had made that part of the directions for docker. If running it straight with node the download works, but it the docker I don't think it was able to write back to the directory to save the file.

**Comment by acalcutt** [comment]
Oh, actually I think it is the port it is coming up on. it is starting on 8080 but the command is saying it is on 80

try 
docker run --rm -it -v $(pwd):/data -p 8080:8080 tileserver-gl --verbose

**Comment by acalcutt** [comment]
I added "-p 80" to docker-entrypoint.sh so it starts on 80 inside the docker like the old release did. I think now it should work with the instuctions you have/site documentation npw

Not sure how it used to start on port 80, since it looks like it default to 8080

**Comment by roblabs** [comment]
@acalcutt — Thanks for the pointing out the port and the patch.  I was successful using your [steps](https://github.com/maptiler/tileserver-gl/pull/602#issuecomment-1248474781).

It now works from both your Docker Hub image & a locally built Docker image.

Thanks!

---

```bash
# Tested with Docker Hub image `wifidb/tileserver-gl`
#  note:  this will change when maptiler accepts the PR
docker run --rm -it -v $(pwd):/data -p 8080:80 wifidb/tileserver-gl
```

> Starting @acalcutt/tileserver-gl v4.0.22
Using specified config file from config.json
Starting server
Listening at http://[::]:80/
Startup complete

---

```bash
# Tested with locally built Docker image `tileserver-gl`
docker run --rm -it -v $(pwd):/data -p 8080:80 tileserver-gl --verbose
```

> Starting tileserver-gl-LOCALLY-BUILT v3.1.1β

---

_Test on `localhost:8080` using Docker Hub & locally built Docker image_
image

**Comment by petrsloup** [comment]
Thanks for the effort !

Tested locally and everything seems to be working fine now, so I'm merging this PR 👍 

I was also thinking about the Dockerfile, which got a little too complicated over time.. Maybe it would make sense to base it on `ubuntu` (and install `node` inside) rather than the `node` image (which is based on debian), so that we can more easily install all the deps from apt instead of hardcoding the `.deb` urls. But I guess that would require some more experimentation..

**Comment by acalcutt** [comment]
I did explorer a few different docker images other than one I chose, but I forget why I decided to go that route. I feel like it was a OS + Node combination I was trying to get but couldn't find already made.

**Comment by pgassmann** [comment]
Thank you @acalcutt for the updates and @petrsloup  for merging this. I already feared this project is unmaintained as the last image on dockerhub is from 2 years ago. I was looking for alternatives and switched to the wifidb image yesterday ;-)

When will you release a new official image?

**Comment by acalcutt** [comment]
I can't speak for when this is released, but I have suggested taking our time releasing this

Currently there is one known bug a static image rendering I am trying to work out with the maplibre-native team here https://github.com/maplibre/maplibre-gl-native/issues/479. the issue with static tiles looks like this ( https://github.com/acalcutt/tileserver-gl/issues/5 ).  I have a custom maplibre-native fix in my fork which seems to fix it, but it seems to break macos builds....so we are still looking at that.

**Pull request merged**
