### PR TITLE
Increase initial timeout - xvfbMaxStartWaitTime

### LINKED ISSUE #386: xdpyinfo:  unable to open display ":99". and xvfbMaxStartWaitTime
I am using tileglserver on docker (klokantech/tileserver-gl)

Trouble:
multiple `xdpyinfo:  unable to open display ":99".` and then `Could not connect to display 99 in 5 seconds time.`

Solution:
copy run.sh from this repo and change xvfbMaxStartWaitTime to 60 seconds (seems my server needs 20 seconds to start xvfb). After that use docker volume to replace run.sh. 
Example for docker-compose
```
    volumes:
      - "./run.sh:/usr/src/app/run.sh"
```

https://github.com/maptiler/tileserver-gl/commit/8e1071aad038b960767f1910d6ea86974496b2e4
@guenhter 

5 seconds is hot enough for some machines.
There is interesting comment in run.sh:
`# Wait to be able to connect to the port. This will exit if it cannot in 15 minutes.` (but there are 5 seconds only)

There is two ways: increase hardcoded timeout or provide the way to set timeout from outside

### PR DESCRIPTION
**Pull request by zstadler**
Resolve #386

### CODE REVIEW

**Comment by zstadler** [comment]
@petrsloup
Please merge this PR and publish to Docker Hub.
The existing short delay is impacting the stability of our website.
Thanks!

**Comment by zstadler** [comment]
Although the comment in the code says the `run.sh` script waits 15-minutes for the display/frame-buffer to be ready, the actual wait is just 5 seconds!
This PR changes the wait to 1 minute and updates the comment accordingly.

**Comment by nyurik** [comment]
cc: @klokan @daliborjanak @MartinMikita -- any objections to this PR?

**Comment by petrsloup** [comment]
This looks like a safe change and should not affect any existing cases where the server successfully starts up. Merged, thanks.

**Comment by lhsm** [comment]
@petrsloup
Please update docker image with this fix

**Pull request merged**
