### PR TITLE
Streamline Dockerfile for caching and size

### PR DESCRIPTION
**Pull request by joakimfors**
Use newer base images and modify Dockerfile to allow for better caching and smaller image file size. Simplify entry script and run as a non-root user.

### CODE REVIEW

**Comment by scara** [comment]
Cool!
If _multi-stage_ cannot be adopted here (Docker 17.05+), _multi-stage_ could be emulated via https://docs.docker.com/develop/develop-images/multistage-build/#before-multi-stage-builds.

HTH,
Matteo

**Comment by petrsloup** [comment]
Cool, but does the simplified script cover all the cases why the original run.sh is so complicated?

There were some concerns especially about the restartability of the container and waiting for xvfb to start up properly.

See https://github.com/maptiler/tileserver-gl/pull/310, https://github.com/maptiler/tileserver-gl/pull/313 and also  https://github.com/maptiler/tileserver-gl/pull/242

**Comment by joakimfors** [comment]
The xvfb-run wrapper script that is included in the Debian xvfb packages takes care of all setup. However, #242 could be a separate issue. Will check that.

**Comment by joakimfors** [comment]
OK, 6b3f557 should cover the same issue as #242

**Comment by petrsloup** [comment]
Thanks, merged.

**Pull request merged**
