### PR TITLE
refactor: add promisified wrapper for MBTiles

### PR DESCRIPTION
**Pull request by akx**
This adds a small wrapper around the `@mapbox/mbtiles` MBTiles class to promisify opening them (instead of callback pyramids).

This opens up avenues to further DRY out the code and make things more async and modern.

### CODE REVIEW

**Comment by akx** [comment]
Okay, rebased post #1320 merge.

**Comment by akx** [comment]
ping @acalcutt :)

**Comment by acalcutt** [comment]
Overall I do think this looks cleaner and I am likely going to merge this. 

This one thing I am wondering about id the file name of the wrapper. It seems like pmtiles_adapter.js and mbtiles_wrapper.js should be named more similarly. That is just really a nitpick thing.

Speaking of pmtiles, I probably did not promisify it very well, so I am wondering if you think there are any improvements there with pmtiles like these changes.

**Comment by akx** [comment]
> This one thing I am wondering about id the file name of the wrapper. It seems like pmtiles_adapter.js and mbtiles_wrapper.js should be named more similarly. That is just really a nitpick thing.

Maybe. I just named the file after the class name, and the class really is just a simple wrapper around `MBTiles` :)

**Review by acalcutt — APPROVED** [review]
Looks cleaner to me. Tested it locally and it seems to work fine

In the future we might want to look at renaming a few of these files, but we can think about it more.

**Pull request merged**
