### PR TITLE
Windows support workaround.

### PR DESCRIPTION
**Pull request by acalcutt**
This is a workaround to allow tileserver-gl to run on windows.

Based on information from [tdcosta100](https://github.com/tdcosta100) about a sharp/canvas incompatibility on windows being caused by a MinGW64/UCRT64 build difference, I was able to work with the node-canvas people to get them to change their windows binary to a [UCRT64 build](https://github.com/Automattic/node-canvas/pull/2219). With this change, canvas 2.11.2 now can work with sharp 0.32.0

There is one other difficulty, which is the order sharp and canvas get imported matters, and unfortunately the order on windows is the opposite of what linux needs (what we have been using). we also can't just change the order of the imports with an if statement, because imports are required to be at the top level.

This PR works around the issue by separating out out the canvas/sharp imports into their own platform specific files. This allows the order to be changed per platform and allows tileserver-gl to run on windows (in addition to previously supported OSs)

With this change, tileserver-gl running on windows and linux!
image

image

### CODE REVIEW

**Comment by scara** [comment]
HI @acalcutt,
great news!

What about adding an `INFO` log telling about the environment on which `tileserver-gl` will start?
I'm thinking about at least both the _OS_ and the _Architecture_.

HTH,
Matteo

**Comment by acalcutt** [comment]
@scara I've updated the npm section of installation.rst to include windows.  I've also updated the layout a little and tried to make it a bit more accurate.

you can view the changes at
https://github.com/WifiDB/tileserver-gl/blob/windows_workaround/docs/installation.rst#native-dependencies

**Comment by scara** [comment]
Hi @acalcutt,
> I've updated the npm section of installation.rst to include windows. 

Thanks!

I still wonder if we should add the "fingerprint" of the underline OS when starting, just for debug/support purposes.

HTH,
Matteo

**Comment by acalcutt** [comment]
I think i misread what you were looking for the first time. I agree, I think os version and architecture are useful in the startup info. 

I added in some code to display os.versions and os.arch on the line with the tileserver version. I think that gives the best information (though it was hard to get exactly the version of the os like I wanted).

It looks like this now
image
image

**Comment by scara** [comment]
Hi @acalcutt,
> I think i misread what you were looking for the first time

No problem.
Thanks for the new data in the log, even if `version()` looks "weird" when running on Linux: `platform()` could be better but we'll miss what is the distro behind that _Linux_ e.g. `#38~20.04.1-Ubuntu SMP Sun Mar 12 04:47:58 UTC 2023`.
On _Linux_ `os.version().split(' ').shift()` could help but it will break the _Windows_ prompt.

BTW guessing that even `arch` is a function i.e. it should be: `${os.arch()}`.

HTH,
Matteo

**Comment by acalcutt** [comment]
This no longer seems to work with the latest version of sharp, so this is proably not the way to go.

**Comment by acalcutt** [comment]
I am closing this since windows support is working in v4.7.0

**Pull request closed without merging**
